package com.fashionsuperman.fs.game.dao.mapper;

import com.fashionsuperman.fs.game.dao.entity.CommodityCatagory;

public interface CommodityCatagoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditycatagory
     *
     * @mbggenerated Mon Mar 27 08:55:32 CST 2017
     */
    int deleteByPrimaryKey(Long catagoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditycatagory
     *
     * @mbggenerated Mon Mar 27 08:55:32 CST 2017
     */
    int insert(CommodityCatagory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditycatagory
     *
     * @mbggenerated Mon Mar 27 08:55:32 CST 2017
     */
    int insertSelective(CommodityCatagory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditycatagory
     *
     * @mbggenerated Mon Mar 27 08:55:32 CST 2017
     */
    CommodityCatagory selectByPrimaryKey(Long catagoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditycatagory
     *
     * @mbggenerated Mon Mar 27 08:55:32 CST 2017
     */
    int updateByPrimaryKeySelective(CommodityCatagory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditycatagory
     *
     * @mbggenerated Mon Mar 27 08:55:32 CST 2017
     */
    int updateByPrimaryKey(CommodityCatagory record);

    /**
     * 根据商品分类名称查询分类
     * @param catagoryname
     * @return
     */
	CommodityCatagory selectByCatagoryName(String catagoryname);

	/**
	 * 主键递增插入
	 * @param commodityCatagory
	 */
	int insertIncrement(CommodityCatagory commodityCatagory);
}