package com.fashionsuperman.fs.game.dao.mapper;

import java.util.List;
import java.util.Map;

import com.fashionsuperman.fs.game.dao.entity.Commodity;
import com.fashionsuperman.fs.game.dao.entity.custom.CommodityCustom;

public interface CommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    int deleteByPrimaryKey(Long commodityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    int insert(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    int insertSelective(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    Commodity selectByPrimaryKey(Long commodityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    int updateByPrimaryKeySelective(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    int updateByPrimaryKey(Commodity record);

    /**
     * 主键递增插入
     * @param commodity
     * @return
     */
	int insertIncrement(Commodity commodity);

	/**
	 * 根据商品名称查询商品
	 * @param commodityname
	 * @return
	 */
	Commodity selectByCommodityName(String commodityname);
	/**
	 * 根据参数查询
	 * @param paramMap
	 * @return
	 */
	List<Commodity> selectByParam(Map<String, Object> paramMap);

	List<Commodity> queryFooCatagoryCommodities(Long catagoryid);

	List<Commodity> queryFooCatagoryCommoditiesAll(Long catagoryid);

	/**
	 * 查询商店内某个商品分类下的所有商品
	 * @param catagoryid
	 * @return
	 */
	List<CommodityCustom> queryFooCatagoryCommoditiesShop(Long catagoryid);
}