package com.fashionsuperman.fs.game.dao.mapper;

import com.fashionsuperman.fs.game.dao.entity.Commodity;

public interface CommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    int deleteByPrimaryKey(Long commodityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    int insert(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    int insertSelective(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    Commodity selectByPrimaryKey(Long commodityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    int updateByPrimaryKeySelective(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    int updateByPrimaryKey(Commodity record);

    /**
     * 主键递增插入
     * @param commodity
     * @return
     */
	int insertIncrement(Commodity commodity);

	/**
	 * 根据商品名称查询商品
	 * @param commodityname
	 * @return
	 */
	Commodity selectByCommodityName(String commodityname);
}