package com.fashionsuperman.fs.game.dao.mapper;

import com.fashionsuperman.fs.game.dao.entity.LoginCount;

public interface LoginCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginCount
     *
     * @mbggenerated Fri Jul 07 13:41:10 CST 2017
     */
    int deleteByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginCount
     *
     * @mbggenerated Fri Jul 07 13:41:10 CST 2017
     */
    int insert(LoginCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginCount
     *
     * @mbggenerated Fri Jul 07 13:41:10 CST 2017
     */
    int insertSelective(LoginCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginCount
     *
     * @mbggenerated Fri Jul 07 13:41:10 CST 2017
     */
    LoginCount selectByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginCount
     *
     * @mbggenerated Fri Jul 07 13:41:10 CST 2017
     */
    int updateByPrimaryKeySelective(LoginCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginCount
     *
     * @mbggenerated Fri Jul 07 13:41:10 CST 2017
     */
    int updateByPrimaryKey(LoginCount record);
}