package com.fashionsuperman.fs.game.dao.mapper;

import com.fashionsuperman.fs.game.dao.entity.NoLoginCount;

public interface NoLoginCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NoLoginCount
     *
     * @mbggenerated Fri Jul 07 13:42:50 CST 2017
     */
    int deleteByPrimaryKey(String randomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NoLoginCount
     *
     * @mbggenerated Fri Jul 07 13:42:50 CST 2017
     */
    int insert(NoLoginCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NoLoginCount
     *
     * @mbggenerated Fri Jul 07 13:42:50 CST 2017
     */
    int insertSelective(NoLoginCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NoLoginCount
     *
     * @mbggenerated Fri Jul 07 13:42:50 CST 2017
     */
    NoLoginCount selectByPrimaryKey(String randomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NoLoginCount
     *
     * @mbggenerated Fri Jul 07 13:42:50 CST 2017
     */
    int updateByPrimaryKeySelective(NoLoginCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NoLoginCount
     *
     * @mbggenerated Fri Jul 07 13:42:50 CST 2017
     */
    int updateByPrimaryKey(NoLoginCount record);
}