package com.fashionsuperman.fs.game.dao.mapper;

import java.util.List;

import com.fashionsuperman.fs.game.dao.entity.Rank;
import com.fashionsuperman.fs.game.dao.entity.custom.RankUser;

public interface RankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Wed Mar 22 11:39:02 CST 2017
     */
    int deleteByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Wed Mar 22 11:39:02 CST 2017
     */
    int insert(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Wed Mar 22 11:39:02 CST 2017
     */
    int insertSelective(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Wed Mar 22 11:39:02 CST 2017
     */
    Rank selectByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Wed Mar 22 11:39:02 CST 2017
     */
    int updateByPrimaryKeySelective(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Wed Mar 22 11:39:02 CST 2017
     */
    int updateByPrimaryKey(Rank record);

	List<RankUser> getUserList();

	Rank selectByAccountName(String accountname);
}