package com.fashionsuperman.fs.game.dao.mapper;

import com.fashionsuperman.fs.game.dao.entity.Sequence;

public interface SequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Sat Apr 29 18:19:56 CST 2017
     */
    int deleteByPrimaryKey(String seqName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Sat Apr 29 18:19:56 CST 2017
     */
    int insert(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Sat Apr 29 18:19:56 CST 2017
     */
    int insertSelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Sat Apr 29 18:19:56 CST 2017
     */
    Sequence selectByPrimaryKey(String seqName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Sat Apr 29 18:19:56 CST 2017
     */
    int updateByPrimaryKeySelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Sat Apr 29 18:19:56 CST 2017
     */
    int updateByPrimaryKey(Sequence record);
    
    Long nextval();
    
    Long currval();
}