package com.fashionsuperman.fs.game.dao.mapper;

import java.util.List;
import java.util.Map;

import com.fashionsuperman.fs.game.dao.entity.Shop;
import com.fashionsuperman.fs.game.dao.entity.custom.ShopCustom;

public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    int deleteByPrimaryKey(Long shopitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    int insertSelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    Shop selectByPrimaryKey(Long shopitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    int updateByPrimaryKeySelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    int updateByPrimaryKey(Shop record);

	List<ShopCustom> selectByParam(Map<String, Object> paramMap);

	/**
	 * 主键递增插入
	 * @param param
	 * @return
	 */
	int insertIncrement(Shop param);
}