package com.fashionsuperman.fs.game.dao.mapper;

import java.util.List;

import com.fashionsuperman.fs.game.dao.entity.UserRelationshipKey;
import com.fashionsuperman.fs.game.dao.entity.custom.UserCustom;

public interface UserRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbggenerated Wed Mar 22 11:03:23 CST 2017
     */
    int deleteByPrimaryKey(UserRelationshipKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbggenerated Wed Mar 22 11:03:23 CST 2017
     */
    int insert(UserRelationshipKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbggenerated Wed Mar 22 11:03:23 CST 2017
     */
    int insertSelective(UserRelationshipKey record);
    /**
     * 获取用户好友列表
     * @param userid
     * @return
     */
	List<UserCustom> selectUserFriends(Long userid);
}