package com.fashionsuperman.fs.game.dao.mapper;

import com.fashionsuperman.fs.game.dao.entity.UserShare;

public interface UserShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usershare
     *
     * @mbggenerated Wed Aug 02 19:59:39 CST 2017
     */
    int deleteByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usershare
     *
     * @mbggenerated Wed Aug 02 19:59:39 CST 2017
     */
    int insert(UserShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usershare
     *
     * @mbggenerated Wed Aug 02 19:59:39 CST 2017
     */
    int insertSelective(UserShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usershare
     *
     * @mbggenerated Wed Aug 02 19:59:39 CST 2017
     */
    UserShare selectByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usershare
     *
     * @mbggenerated Wed Aug 02 19:59:39 CST 2017
     */
    int updateByPrimaryKeySelective(UserShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usershare
     *
     * @mbggenerated Wed Aug 02 19:59:39 CST 2017
     */
    int updateByPrimaryKey(UserShare record);
}