package com.fashionsuperman.fs.game.dao.mapper;

import java.util.List;
import java.util.Map;

import com.fashionsuperman.fs.game.dao.entity.Package;
import com.fashionsuperman.fs.game.dao.entity.UserPackageKey;
import com.fashionsuperman.fs.game.dao.entity.custom.UserPackageListCustom;

public interface UserPackageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpackage
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    int deleteByPrimaryKey(UserPackageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpackage
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    int insert(UserPackageKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpackage
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    int insertSelective(UserPackageKey record);
    
    /**
     * 获取用户背包
     * @param paramMap
     * @return
     */
	List<UserPackageListCustom> getUserPackageList(Map<String, Object> paramMap);

	/**
	 * 获取用户背包中某件商品的数量
	 * @param paramMap
	 * @return
	 */
	int getUserFooCommodityNum(Map<String, Object> paramMap);

	/**
	 * 获取某用户的某个商品背包 
	 * @param paramMap
	 * @return
	 */
	Package selectFooUserFooCommodity(Map<String, Object> paramMap);

	/**
	 * 获取用户背包列表,管理后台用
	 * @param userId
	 * @return
	 */
	List<com.fashionsuperman.fs.game.dao.entity.custom.ResGetUserPackageList> getUserPackageList2(Long userId);
}