package com.fashionsuperman.fs.game.dao.entity;

public class CommodityCatagory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commoditycatagory.CatagoryId
     *
     * @mbggenerated Mon Mar 27 08:55:32 CST 2017
     */
    private Long catagoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commoditycatagory.CatagoryName
     *
     * @mbggenerated Mon Mar 27 08:55:32 CST 2017
     */
    private String catagoryname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commoditycatagory.CatagoryId
     *
     * @return the value of commoditycatagory.CatagoryId
     *
     * @mbggenerated Mon Mar 27 08:55:32 CST 2017
     */
    public Long getCatagoryid() {
        return catagoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commoditycatagory.CatagoryId
     *
     * @param catagoryid the value for commoditycatagory.CatagoryId
     *
     * @mbggenerated Mon Mar 27 08:55:32 CST 2017
     */
    public void setCatagoryid(Long catagoryid) {
        this.catagoryid = catagoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commoditycatagory.CatagoryName
     *
     * @return the value of commoditycatagory.CatagoryName
     *
     * @mbggenerated Mon Mar 27 08:55:32 CST 2017
     */
    public String getCatagoryname() {
        return catagoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commoditycatagory.CatagoryName
     *
     * @param catagoryname the value for commoditycatagory.CatagoryName
     *
     * @mbggenerated Mon Mar 27 08:55:32 CST 2017
     */
    public void setCatagoryname(String catagoryname) {
        this.catagoryname = catagoryname;
    }
}