package com.fashionsuperman.fs.game.dao.entity;

public class Commodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.CommodityId
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    private Long commodityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.CommodityCatagoryId
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    private Long commoditycatagoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.CommodityName
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    private String commodityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.CommodityDes
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    private String commoditydes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.CommodityId
     *
     * @return the value of commodity.CommodityId
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    public Long getCommodityid() {
        return commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.CommodityId
     *
     * @param commodityid the value for commodity.CommodityId
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    public void setCommodityid(Long commodityid) {
        this.commodityid = commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.CommodityCatagoryId
     *
     * @return the value of commodity.CommodityCatagoryId
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    public Long getCommoditycatagoryid() {
        return commoditycatagoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.CommodityCatagoryId
     *
     * @param commoditycatagoryid the value for commodity.CommodityCatagoryId
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    public void setCommoditycatagoryid(Long commoditycatagoryid) {
        this.commoditycatagoryid = commoditycatagoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.CommodityName
     *
     * @return the value of commodity.CommodityName
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    public String getCommodityname() {
        return commodityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.CommodityName
     *
     * @param commodityname the value for commodity.CommodityName
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    public void setCommodityname(String commodityname) {
        this.commodityname = commodityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.CommodityDes
     *
     * @return the value of commodity.CommodityDes
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    public String getCommoditydes() {
        return commoditydes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.CommodityDes
     *
     * @param commoditydes the value for commodity.CommodityDes
     *
     * @mbggenerated Fri Mar 24 16:10:52 CST 2017
     */
    public void setCommoditydes(String commoditydes) {
        this.commoditydes = commoditydes;
    }
}