package com.fashionsuperman.fs.game.dao.entity;

import java.util.Date;

public class LoginCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginCount.UserId
     *
     * @mbggenerated Fri Jul 07 13:41:10 CST 2017
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginCount.Number
     *
     * @mbggenerated Fri Jul 07 13:41:10 CST 2017
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginCount.UpdateDate
     *
     * @mbggenerated Fri Jul 07 13:41:10 CST 2017
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginCount.UserId
     *
     * @return the value of LoginCount.UserId
     *
     * @mbggenerated Fri Jul 07 13:41:10 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginCount.UserId
     *
     * @param userid the value for LoginCount.UserId
     *
     * @mbggenerated Fri Jul 07 13:41:10 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginCount.Number
     *
     * @return the value of LoginCount.Number
     *
     * @mbggenerated Fri Jul 07 13:41:10 CST 2017
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginCount.Number
     *
     * @param number the value for LoginCount.Number
     *
     * @mbggenerated Fri Jul 07 13:41:10 CST 2017
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginCount.UpdateDate
     *
     * @return the value of LoginCount.UpdateDate
     *
     * @mbggenerated Fri Jul 07 13:41:10 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginCount.UpdateDate
     *
     * @param updatedate the value for LoginCount.UpdateDate
     *
     * @mbggenerated Fri Jul 07 13:41:10 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}