package com.fashionsuperman.fs.game.dao.entity;

import java.util.Date;

public class NoLoginCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NoLoginCount.RandomId
     *
     * @mbggenerated Fri Jul 07 13:42:50 CST 2017
     */
    private String randomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NoLoginCount.Number
     *
     * @mbggenerated Fri Jul 07 13:42:50 CST 2017
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NoLoginCount.UpdateTime
     *
     * @mbggenerated Fri Jul 07 13:42:50 CST 2017
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NoLoginCount.RandomId
     *
     * @return the value of NoLoginCount.RandomId
     *
     * @mbggenerated Fri Jul 07 13:42:50 CST 2017
     */
    public String getRandomid() {
        return randomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NoLoginCount.RandomId
     *
     * @param randomid the value for NoLoginCount.RandomId
     *
     * @mbggenerated Fri Jul 07 13:42:50 CST 2017
     */
    public void setRandomid(String randomid) {
        this.randomid = randomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NoLoginCount.Number
     *
     * @return the value of NoLoginCount.Number
     *
     * @mbggenerated Fri Jul 07 13:42:50 CST 2017
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NoLoginCount.Number
     *
     * @param number the value for NoLoginCount.Number
     *
     * @mbggenerated Fri Jul 07 13:42:50 CST 2017
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NoLoginCount.UpdateTime
     *
     * @return the value of NoLoginCount.UpdateTime
     *
     * @mbggenerated Fri Jul 07 13:42:50 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NoLoginCount.UpdateTime
     *
     * @param updatetime the value for NoLoginCount.UpdateTime
     *
     * @mbggenerated Fri Jul 07 13:42:50 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}