package com.fashionsuperman.fs.game.dao.entity;

public class Package {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.PackageId
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    private Long packageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.CommodityId
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    private Long commodityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.Number
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.PackageId
     *
     * @return the value of package.PackageId
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    public Long getPackageid() {
        return packageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.PackageId
     *
     * @param packageid the value for package.PackageId
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    public void setPackageid(Long packageid) {
        this.packageid = packageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.CommodityId
     *
     * @return the value of package.CommodityId
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    public Long getCommodityid() {
        return commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.CommodityId
     *
     * @param commodityid the value for package.CommodityId
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    public void setCommodityid(Long commodityid) {
        this.commodityid = commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.Number
     *
     * @return the value of package.Number
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.Number
     *
     * @param number the value for package.Number
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}