package com.fashionsuperman.fs.game.dao.entity;

public class Rank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.UserId
     *
     * @mbggenerated Wed Mar 22 11:39:02 CST 2017
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.NickName
     *
     * @mbggenerated Wed Mar 22 11:39:02 CST 2017
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.Score
     *
     * @mbggenerated Wed Mar 22 11:39:02 CST 2017
     */
    private Float score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.UserId
     *
     * @return the value of rank.UserId
     *
     * @mbggenerated Wed Mar 22 11:39:02 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.UserId
     *
     * @param userid the value for rank.UserId
     *
     * @mbggenerated Wed Mar 22 11:39:02 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.NickName
     *
     * @return the value of rank.NickName
     *
     * @mbggenerated Wed Mar 22 11:39:02 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.NickName
     *
     * @param nickname the value for rank.NickName
     *
     * @mbggenerated Wed Mar 22 11:39:02 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.Score
     *
     * @return the value of rank.Score
     *
     * @mbggenerated Wed Mar 22 11:39:02 CST 2017
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.Score
     *
     * @param score the value for rank.Score
     *
     * @mbggenerated Wed Mar 22 11:39:02 CST 2017
     */
    public void setScore(Float score) {
        this.score = score;
    }
}