package com.fashionsuperman.fs.game.dao.entity;

public class Sequence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.seq_name
     *
     * @mbggenerated Sat Apr 29 18:19:56 CST 2017
     */
    private String seqName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.current_val
     *
     * @mbggenerated Sat Apr 29 18:19:56 CST 2017
     */
    private Long currentVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.increment_val
     *
     * @mbggenerated Sat Apr 29 18:19:56 CST 2017
     */
    private Long incrementVal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.seq_name
     *
     * @return the value of sequence.seq_name
     *
     * @mbggenerated Sat Apr 29 18:19:56 CST 2017
     */
    public String getSeqName() {
        return seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.seq_name
     *
     * @param seqName the value for sequence.seq_name
     *
     * @mbggenerated Sat Apr 29 18:19:56 CST 2017
     */
    public void setSeqName(String seqName) {
        this.seqName = seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.current_val
     *
     * @return the value of sequence.current_val
     *
     * @mbggenerated Sat Apr 29 18:19:56 CST 2017
     */
    public Long getCurrentVal() {
        return currentVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.current_val
     *
     * @param currentVal the value for sequence.current_val
     *
     * @mbggenerated Sat Apr 29 18:19:56 CST 2017
     */
    public void setCurrentVal(Long currentVal) {
        this.currentVal = currentVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.increment_val
     *
     * @return the value of sequence.increment_val
     *
     * @mbggenerated Sat Apr 29 18:19:56 CST 2017
     */
    public Long getIncrementVal() {
        return incrementVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.increment_val
     *
     * @param incrementVal the value for sequence.increment_val
     *
     * @mbggenerated Sat Apr 29 18:19:56 CST 2017
     */
    public void setIncrementVal(Long incrementVal) {
        this.incrementVal = incrementVal;
    }
}