package com.fashionsuperman.fs.game.dao.entity;

public class Shop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.ShopItemId
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    private Long shopitemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.CommodityId
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    private Long commodityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.Number
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.Price
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.UserId
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.Discount
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    private Float discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.DiscountDes
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    private String discountdes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.ShopItemId
     *
     * @return the value of shop.ShopItemId
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    public Long getShopitemid() {
        return shopitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.ShopItemId
     *
     * @param shopitemid the value for shop.ShopItemId
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    public void setShopitemid(Long shopitemid) {
        this.shopitemid = shopitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.CommodityId
     *
     * @return the value of shop.CommodityId
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    public Long getCommodityid() {
        return commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.CommodityId
     *
     * @param commodityid the value for shop.CommodityId
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    public void setCommodityid(Long commodityid) {
        this.commodityid = commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.Number
     *
     * @return the value of shop.Number
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.Number
     *
     * @param number the value for shop.Number
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.Price
     *
     * @return the value of shop.Price
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.Price
     *
     * @param price the value for shop.Price
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.UserId
     *
     * @return the value of shop.UserId
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.UserId
     *
     * @param userid the value for shop.UserId
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.Discount
     *
     * @return the value of shop.Discount
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    public Float getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.Discount
     *
     * @param discount the value for shop.Discount
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    public void setDiscount(Float discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.DiscountDes
     *
     * @return the value of shop.DiscountDes
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    public String getDiscountdes() {
        return discountdes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.DiscountDes
     *
     * @param discountdes the value for shop.DiscountDes
     *
     * @mbggenerated Mon Apr 17 21:12:34 CST 2017
     */
    public void setDiscountdes(String discountdes) {
        this.discountdes = discountdes;
    }
}