package com.fashionsuperman.fs.game.dao.entity;

public class UserShare {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usershare.UserId
     *
     * @mbggenerated Wed Aug 02 19:59:39 CST 2017
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usershare.Flag
     *
     * @mbggenerated Wed Aug 02 19:59:39 CST 2017
     */
    private String flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usershare.UserId
     *
     * @return the value of usershare.UserId
     *
     * @mbggenerated Wed Aug 02 19:59:39 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usershare.UserId
     *
     * @param userid the value for usershare.UserId
     *
     * @mbggenerated Wed Aug 02 19:59:39 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usershare.Flag
     *
     * @return the value of usershare.Flag
     *
     * @mbggenerated Wed Aug 02 19:59:39 CST 2017
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usershare.Flag
     *
     * @param flag the value for usershare.Flag
     *
     * @mbggenerated Wed Aug 02 19:59:39 CST 2017
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }
}