package com.fashionsuperman.fs.game.dao.entity;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.UserId
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	private Long userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.AccountName
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	private String accountname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.NickName
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.ForeighId
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	private String foreighid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.ForeighType
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	private String foreightype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.Funds
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	private Float funds;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.CreateDate
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.Password
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.UserId
	 * @return  the value of user.UserId
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.UserId
	 * @param userid  the value for user.UserId
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.AccountName
	 * @return  the value of user.AccountName
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public String getAccountname() {
		return accountname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.AccountName
	 * @param accountname  the value for user.AccountName
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public void setAccountname(String accountname) {
		this.accountname = accountname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.NickName
	 * @return  the value of user.NickName
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.NickName
	 * @param nickname  the value for user.NickName
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.ForeighId
	 * @return  the value of user.ForeighId
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public String getForeighid() {
		return foreighid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.ForeighId
	 * @param foreighid  the value for user.ForeighId
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public void setForeighid(String foreighid) {
		this.foreighid = foreighid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.ForeighType
	 * @return  the value of user.ForeighType
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public String getForeightype() {
		return foreightype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.ForeighType
	 * @param foreightype  the value for user.ForeighType
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public void setForeightype(String foreightype) {
		this.foreightype = foreightype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.Funds
	 * @return  the value of user.Funds
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public Float getFunds() {
		return funds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.Funds
	 * @param funds  the value for user.Funds
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public void setFunds(Float funds) {
		this.funds = funds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.CreateDate
	 * @return  the value of user.CreateDate
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.CreateDate
	 * @param createdate  the value for user.CreateDate
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.Password
	 * @return  the value of user.Password
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.Password
	 * @param password  the value for user.Password
	 * @mbggenerated  Wed Mar 22 09:47:29 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}