package com.fashionsuperman.fs.game.dao.entity;

public class UserPackageKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpackage.PackageId
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    private Long packageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpackage.UserId
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    private Long userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpackage.PackageId
     *
     * @return the value of userpackage.PackageId
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    public Long getPackageid() {
        return packageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpackage.PackageId
     *
     * @param packageid the value for userpackage.PackageId
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    public void setPackageid(Long packageid) {
        this.packageid = packageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpackage.UserId
     *
     * @return the value of userpackage.UserId
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpackage.UserId
     *
     * @param userid the value for userpackage.UserId
     *
     * @mbggenerated Mon Apr 24 20:53:54 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }
}