package com.fashionsuperman.fs.game.dao.entity;

public class UserRelationshipKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrelationship.AUserId
     *
     * @mbggenerated Wed Mar 22 11:03:23 CST 2017
     */
    private Long auserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrelationship.BUserId
     *
     * @mbggenerated Wed Mar 22 11:03:23 CST 2017
     */
    private Long buserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrelationship.AUserId
     *
     * @return the value of userrelationship.AUserId
     *
     * @mbggenerated Wed Mar 22 11:03:23 CST 2017
     */
    public Long getAuserid() {
        return auserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrelationship.AUserId
     *
     * @param auserid the value for userrelationship.AUserId
     *
     * @mbggenerated Wed Mar 22 11:03:23 CST 2017
     */
    public void setAuserid(Long auserid) {
        this.auserid = auserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrelationship.BUserId
     *
     * @return the value of userrelationship.BUserId
     *
     * @mbggenerated Wed Mar 22 11:03:23 CST 2017
     */
    public Long getBuserid() {
        return buserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrelationship.BUserId
     *
     * @param buserid the value for userrelationship.BUserId
     *
     * @mbggenerated Wed Mar 22 11:03:23 CST 2017
     */
    public void setBuserid(Long buserid) {
        this.buserid = buserid;
    }
}